SELECT DISTINCT NOW.N,
    CASE WHEN PARENT.N iS NULL THEN 'Root'
         WHEN CHILD.N iS NULL THEN 'Leaf'
         ELSE 'Inner'
         END
FROM BST NOW
    LEFT JOIN BST PARENT ON NOW.P = PARENT.N
    LEFT JOIN BST CHILD ON CHILD.P = NOW.N
ORDER BY NOW.N